export const Users = [
  {
    id: 1,
    profilePicture: "/assest/person/1.avif",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "/assest/person/2.avif",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "assest/person/3.avif",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "assest/person/4.avif",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "assest/person/5.avif",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "assest/person/6.avif",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "assest/person/7.avif",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "assest/person/8.avif",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "assest/person/9.avif",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "assest/person/10.avif",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/1.avif",
    date: "5 m",
    userId: 1,
    like: 32,
    comment: 9,
    share: 10,
  },
  {
    id: 2,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/2.avif",
    date: "15 m",
    userId: 2,
    like: 2,
    comment: 1,
    share: 25,
  },
  {
    id: 3,
    desc: "Love For All, Hatred For None.",
    desc: "Every moment is a fresh beginning.",
    photo: "assest/post/3.avif",
    date: "1 h",
    userId: 3,
    like: 61,
    comment: 2,
    share: 5,
  },
  {
    id: 4,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/4.avif",
    date: "4 h",
    userId: 4,
    like: 7,
    comment: 3,
    share: 7,
  },
  {
    id: 5,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/5.avif",
    date: "5 h",
    userId: 5,
    like: 23,
    comment: 5,
    share: 15,
  },
  {
    id: 6,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/6.avif",
    date: "1 d",
    userId: 6,
    like: 44,
    comment: 6,
    share: 12,
  },
  {
    id: 7,
    desc: "Love For All, Hatred For None.",
    desc: "Never regret anything that made you smile.",
    photo: "assest/post/7.avif",
    date: "2 d",
    userId: 7,
    like: 52,
    comment: 3,
    share: 22,
  },
  {
    id: 8,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/8.avif",
    date: "3 d",
    userId: 8,
    like: 15,
    comment: 1,
    share: 32,
  },
  {
    id: 9,
    desc: "Love For All, Hatred For None.",
    desc: "Change the world by being yourself.",
    photo: "assest/post/9.avif",
    date: "5 d",
    userId: 9,
    like: 11,
    comment: 2,
    share: 19,
  },
  {
    id: 10,
    desc: "Love For All, Hatred For None.",
    photo: "assest/post/10.avif",
    date: "1 w",
    userId: 10,
    like: 104,
    comment: 12,
    share: 27,
  },
];
